[package]
name = "blueberry"
version = "0.1.0"
authors = ["Aditya Diwakar <aditya@diwakar.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.24.0"
futures = "0.3.4"
tokio = "0.2.19"